<?php

namespace Database\Seeders;

use App\Models\HorarioAtencion;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Factories\Sequence;

class HorariosAtencionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Formulacion de Reclamos (delegacion Capital)
        HorarioAtencion::create([
            //'tipo_tramite_id' => '2',
            'oficina_id' => '14',
            'dia_id' => '1',
            'horario_inicio' => '08:00:00',
            'horario_fin' => '13:00:00',
            'cant_max_turno' => 5,
            'intervalo_turno' => '60',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '14',
            'dia_id' => '2',
            'horario_inicio' => '08:00:00',
            'horario_fin' => '13:00:00',
            'cant_max_turno' => 5,
            'intervalo_turno' => '60',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '14',
            'dia_id' => '3',
            'horario_inicio' => '08:00:00',
            'horario_fin' => '13:00:00',
            'cant_max_turno' => 5,
            'intervalo_turno' => '60',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '14',
            'dia_id' => '4',
            'horario_inicio' => '08:00:00',
            'horario_fin' => '13:00:00',
            'cant_max_turno' => 5,
            'intervalo_turno' => '60',
        ]);

        //Mesa de Entrada (delegacion Capital)
        HorarioAtencion::create([
            'oficina_id' => '25',
            'dia_id' => '2',
            'horario_inicio' => '08:00:00',
            'horario_fin' => '13:00:00',
            'cant_max_turno' => 5,
            'intervalo_turno' => '60',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '25',
            'dia_id' => '4',
            'horario_inicio' => '08:00:00',
            'horario_fin' => '13:00:00',
            'cant_max_turno' => 5,
            'intervalo_turno' => '60',
        ]);
        //Ratificaciones (delegacion Capital)
         HorarioAtencion::create([
            'oficina_id' => '36',
            'dia_id' => '1',
            'horario_inicio' => '08:30:00',
            'horario_fin' => '12:30:00',
            'cant_max_turno' => 4,
            'intervalo_turno' => '60',
        ]);
         HorarioAtencion::create([
            'oficina_id' => '36',
            'dia_id' => '2',
            'horario_inicio' => '08:30:00',
            'horario_fin' => '12:30:00',
            'cant_max_turno' => 4,
            'intervalo_turno' => '60',
        ]);
         HorarioAtencion::create([
            'oficina_id' => '36',
            'dia_id' => '3',
            'horario_inicio' => '08:30:00',
            'horario_fin' => '12:30:00',
            'cant_max_turno' => 4,
            'intervalo_turno' => '60',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '36',
            'dia_id' => '4',
            'horario_inicio' => '08:30:00',
            'horario_fin' => '12:30:00',
            'cant_max_turno' => 4,
            'intervalo_turno' => '60',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '36',
            'dia_id' => '5',
            'horario_inicio' => '08:30:00',
            'horario_fin' => '12:30:00',
            'cant_max_turno' => 4,
            'intervalo_turno' => '60',
        ]);

        //Presentacion de Documentacion (delegacion Capital)
        HorarioAtencion::create([
            'oficina_id' => '47',
            'dia_id' => '1',
            'horario_inicio' => '07:30:00',
            'horario_fin' => '12:00:00',
            'cant_max_turno' => 2,
            'intervalo_turno' => '135',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '47',
            'dia_id' => '2',
            'horario_inicio' => '07:30:00',
            'horario_fin' => '12:00:00',
            'cant_max_turno' => 2,
            'intervalo_turno' => '135',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '47',
            'dia_id' => '3',
            'horario_inicio' => '07:30:00',
            'horario_fin' => '12:00:00',
            'cant_max_turno' => 2,
            'intervalo_turno' => '135',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '47',
            'dia_id' => '4',
            'horario_inicio' => '07:30:00',
            'horario_fin' => '12:00:00',
            'cant_max_turno' => 2,
            'intervalo_turno' => '135',
        ]);

        //Retiro de Documentacion (delegacion Capital)
        HorarioAtencion::create([
            'oficina_id' => '58',
            'dia_id' => '1',
            'horario_inicio' => '07:30:00',
            'horario_fin' => '11:30:00',
            'cant_max_turno' => 16,
            'intervalo_turno' => '15',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '58',
            'dia_id' => '2',
            'horario_inicio' => '07:30:00',
            'horario_fin' => '11:30:00',
            'cant_max_turno' => 16,
            'intervalo_turno' => '15',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '58',
            'dia_id' => '3',
            'horario_inicio' => '07:30:00',
            'horario_fin' => '11:30:00',
            'cant_max_turno' => 16,
            'intervalo_turno' => '15',
        ]);
        HorarioAtencion::create([
            'oficina_id' => '58',
            'dia_id' => '4',
            'horario_inicio' => '07:30:00',
            'horario_fin' => '11:30:00',
            'cant_max_turno' => 16,
            'intervalo_turno' => '15',
        ]);
        //Rubrica (delegacion Capital)
         HorarioAtencion::factory()->count(4)->state(new Sequence(
             ['dia_id' => '1'],
             ['dia_id' => '2'],
             ['dia_id' => '3'],
             ['dia_id' => '4'],
        
         ))->create(['oficina_id' => '69',
                   'horario_inicio' => '08:00:00',
                   'horario_fin' => '12:00:00',
                   'cant_max_turno' => 5,
                   'intervalo_turno' => '60',]);

         //Asesoramiento Juridico Gratuito (delegacion Capital)
         HorarioAtencion::factory()->count(4)->state(new Sequence(
            ['dia_id' => '1'],
            ['dia_id' => '2'],
            ['dia_id' => '3'],
            ['dia_id' => '4'],
        ))->create(['oficina_id' => '3',
                  'horario_inicio' => '08:00:00',
                  'horario_fin' => '12:00:00',
                  'cant_max_turno' => 5,
                  'intervalo_turno' => '60',]);

          //(Restantes Oficinas, Dia Lunes)
          HorarioAtencion::factory()->count(70)->state(new Sequence(
            ['oficina_id' => '1'],
            ['oficina_id' => '2'],
            // ['oficina_id' => '3'],
            ['oficina_id' => '4'],
            ['oficina_id' => '5'],
            ['oficina_id' => '6'],
            ['oficina_id' => '7'],
            ['oficina_id' => '8'],
            ['oficina_id' => '9'],
            ['oficina_id' => '10'],
            ['oficina_id' => '11'],
            ['oficina_id' => '12'],
            ['oficina_id' => '13'],
            // ['oficina_id' => '14'],
            ['oficina_id' => '15'],
            ['oficina_id' => '16'],
            ['oficina_id' => '17'],
            ['oficina_id' => '18'],
            ['oficina_id' => '19'],
            ['oficina_id' => '20'],
            ['oficina_id' => '21'],
            ['oficina_id' => '22'],
            ['oficina_id' => '23'],
            ['oficina_id' => '24'],
            // ['oficina_id' => '25'],
            ['oficina_id' => '26'],
            ['oficina_id' => '27'],
            ['oficina_id' => '28'],
            ['oficina_id' => '29'],
            ['oficina_id' => '30'],
            ['oficina_id' => '31'],
            ['oficina_id' => '32'],
            ['oficina_id' => '33'],
            ['oficina_id' => '34'],
            ['oficina_id' => '35'],
            // ['oficina_id' => '36'],
            ['oficina_id' => '37'],
            ['oficina_id' => '38'],
            ['oficina_id' => '39'],
            ['oficina_id' => '40'],
            ['oficina_id' => '41'],
            ['oficina_id' => '42'],
            ['oficina_id' => '43'],
            ['oficina_id' => '44'],
            ['oficina_id' => '45'],
            ['oficina_id' => '46'],
            // ['oficina_id' => '47'],
            ['oficina_id' => '48'],
            ['oficina_id' => '49'],
            ['oficina_id' => '50'],
            ['oficina_id' => '51'],
            ['oficina_id' => '52'],
            ['oficina_id' => '53'],
            ['oficina_id' => '54'],
            ['oficina_id' => '55'],
            ['oficina_id' => '56'],
            ['oficina_id' => '57'],
            // ['oficina_id' => '58'],
            ['oficina_id' => '59'],
            ['oficina_id' => '60'],
            ['oficina_id' => '61'],
            ['oficina_id' => '62'],
            ['oficina_id' => '63'],
            ['oficina_id' => '64'],
            ['oficina_id' => '65'],
            ['oficina_id' => '66'],
            ['oficina_id' => '67'],
            ['oficina_id' => '68'],
            // ['oficina_id' => '69'],
            ['oficina_id' => '70'],
            ['oficina_id' => '71'],
            ['oficina_id' => '72'],
            ['oficina_id' => '73'],
            ['oficina_id' => '74'],
            ['oficina_id' => '75'],
            ['oficina_id' => '76'],
            ['oficina_id' => '77'],
            ['oficina_id' => '78'],
            ['oficina_id' => '79'],
            ['oficina_id' => '70'],
            ['oficina_id' => '71'],
            ['oficina_id' => '72'],
            ['oficina_id' => '73'],
            ['oficina_id' => '74'],
            ['oficina_id' => '75'],
            ['oficina_id' => '76'],
            ['oficina_id' => '77'],
        ))->create(['dia_id' => '1',
                  'horario_inicio' => '08:00:00',
                  'horario_fin' => '12:00:00',
                  'cant_max_turno' => 5,
                  'intervalo_turno' => '60',]);
                  
        //(Restantes Oficinas, Dia Martes)
        HorarioAtencion::factory()->count(70)->state(new Sequence(
            ['oficina_id' => '1'],
            ['oficina_id' => '2'],
            // ['oficina_id' => '3'],
            ['oficina_id' => '4'],
            ['oficina_id' => '5'],
            ['oficina_id' => '6'],
            ['oficina_id' => '7'],
            ['oficina_id' => '8'],
            ['oficina_id' => '9'],
            ['oficina_id' => '10'],
            ['oficina_id' => '11'],
            ['oficina_id' => '12'],
            ['oficina_id' => '13'],
            // ['oficina_id' => '14'],
            ['oficina_id' => '15'],
            ['oficina_id' => '16'],
            ['oficina_id' => '17'],
            ['oficina_id' => '18'],
            ['oficina_id' => '19'],
            ['oficina_id' => '20'],
            ['oficina_id' => '21'],
            ['oficina_id' => '22'],
            ['oficina_id' => '23'],
            ['oficina_id' => '24'],
            // ['oficina_id' => '25'],
            ['oficina_id' => '26'],
            ['oficina_id' => '27'],
            ['oficina_id' => '28'],
            ['oficina_id' => '29'],
            ['oficina_id' => '30'],
            ['oficina_id' => '31'],
            ['oficina_id' => '32'],
            ['oficina_id' => '33'],
            ['oficina_id' => '34'],
            ['oficina_id' => '35'],
            // ['oficina_id' => '36'],
            ['oficina_id' => '37'],
            ['oficina_id' => '38'],
            ['oficina_id' => '39'],
            ['oficina_id' => '40'],
            ['oficina_id' => '41'],
            ['oficina_id' => '42'],
            ['oficina_id' => '43'],
            ['oficina_id' => '44'],
            ['oficina_id' => '45'],
            ['oficina_id' => '46'],
            // ['oficina_id' => '47'],
            ['oficina_id' => '48'],
            ['oficina_id' => '49'],
            ['oficina_id' => '50'],
            ['oficina_id' => '51'],
            ['oficina_id' => '52'],
            ['oficina_id' => '53'],
            ['oficina_id' => '54'],
            ['oficina_id' => '55'],
            ['oficina_id' => '56'],
            ['oficina_id' => '57'],
            // ['oficina_id' => '58'],
            ['oficina_id' => '59'],
            ['oficina_id' => '60'],
            ['oficina_id' => '61'],
            ['oficina_id' => '62'],
            ['oficina_id' => '63'],
            ['oficina_id' => '64'],
            ['oficina_id' => '65'],
            ['oficina_id' => '66'],
            ['oficina_id' => '67'],
            ['oficina_id' => '68'],
            // ['oficina_id' => '69'],
            ['oficina_id' => '70'],
            ['oficina_id' => '71'],
            ['oficina_id' => '72'],
            ['oficina_id' => '73'],
            ['oficina_id' => '74'],
            ['oficina_id' => '75'],
            ['oficina_id' => '76'],
            ['oficina_id' => '77'],
            ['oficina_id' => '78'],
            ['oficina_id' => '79'],
            ['oficina_id' => '70'],
            ['oficina_id' => '71'],
            ['oficina_id' => '72'],
            ['oficina_id' => '73'],
            ['oficina_id' => '74'],
            ['oficina_id' => '75'],
            ['oficina_id' => '76'],
            ['oficina_id' => '77'],
        ))->create(['dia_id' => '2',
                  'horario_inicio' => '08:00:00',
                  'horario_fin' => '12:00:00',
                  'cant_max_turno' => 5,
                  'intervalo_turno' => '60',]); 
        
        //(Restantes Oficinas, Dia Miercoles)
        HorarioAtencion::factory()->count(70)->state(new Sequence(
            ['oficina_id' => '1'],
            ['oficina_id' => '2'],
            // ['oficina_id' => '3'],
            ['oficina_id' => '4'],
            ['oficina_id' => '5'],
            ['oficina_id' => '6'],
            ['oficina_id' => '7'],
            ['oficina_id' => '8'],
            ['oficina_id' => '9'],
            ['oficina_id' => '10'],
            ['oficina_id' => '11'],
            ['oficina_id' => '12'],
            ['oficina_id' => '13'],
            // ['oficina_id' => '14'],
            ['oficina_id' => '15'],
            ['oficina_id' => '16'],
            ['oficina_id' => '17'],
            ['oficina_id' => '18'],
            ['oficina_id' => '19'],
            ['oficina_id' => '20'],
            ['oficina_id' => '21'],
            ['oficina_id' => '22'],
            ['oficina_id' => '23'],
            ['oficina_id' => '24'],
            // ['oficina_id' => '25'],
            ['oficina_id' => '26'],
            ['oficina_id' => '27'],
            ['oficina_id' => '28'],
            ['oficina_id' => '29'],
            ['oficina_id' => '30'],
            ['oficina_id' => '31'],
            ['oficina_id' => '32'],
            ['oficina_id' => '33'],
            ['oficina_id' => '34'],
            ['oficina_id' => '35'],
            // ['oficina_id' => '36'],
            ['oficina_id' => '37'],
            ['oficina_id' => '38'],
            ['oficina_id' => '39'],
            ['oficina_id' => '40'],
            ['oficina_id' => '41'],
            ['oficina_id' => '42'],
            ['oficina_id' => '43'],
            ['oficina_id' => '44'],
            ['oficina_id' => '45'],
            ['oficina_id' => '46'],
            // ['oficina_id' => '47'],
            ['oficina_id' => '48'],
            ['oficina_id' => '49'],
            ['oficina_id' => '50'],
            ['oficina_id' => '51'],
            ['oficina_id' => '52'],
            ['oficina_id' => '53'],
            ['oficina_id' => '54'],
            ['oficina_id' => '55'],
            ['oficina_id' => '56'],
            ['oficina_id' => '57'],
            // ['oficina_id' => '58'],
            ['oficina_id' => '59'],
            ['oficina_id' => '60'],
            ['oficina_id' => '61'],
            ['oficina_id' => '62'],
            ['oficina_id' => '63'],
            ['oficina_id' => '64'],
            ['oficina_id' => '65'],
            ['oficina_id' => '66'],
            ['oficina_id' => '67'],
            ['oficina_id' => '68'],
            // ['oficina_id' => '69'],
            ['oficina_id' => '70'],
            ['oficina_id' => '71'],
            ['oficina_id' => '72'],
            ['oficina_id' => '73'],
            ['oficina_id' => '74'],
            ['oficina_id' => '75'],
            ['oficina_id' => '76'],
            ['oficina_id' => '77'],
            ['oficina_id' => '78'],
            ['oficina_id' => '79'],
            ['oficina_id' => '70'],
            ['oficina_id' => '71'],
            ['oficina_id' => '72'],
            ['oficina_id' => '73'],
            ['oficina_id' => '74'],
            ['oficina_id' => '75'],
            ['oficina_id' => '76'],
            ['oficina_id' => '77'],
        ))->create(['dia_id' => '3',
                  'horario_inicio' => '08:00:00',
                  'horario_fin' => '12:00:00',
                  'cant_max_turno' => 5,
                  'intervalo_turno' => '60',]);   
                  
        //(Restantes Oficinas, Dia Jueves)
        HorarioAtencion::factory()->count(70)->state(new Sequence(
            ['oficina_id' => '1'],
            ['oficina_id' => '2'],
            // ['oficina_id' => '3'],
            ['oficina_id' => '4'],
            ['oficina_id' => '5'],
            ['oficina_id' => '6'],
            ['oficina_id' => '7'],
            ['oficina_id' => '8'],
            ['oficina_id' => '9'],
            ['oficina_id' => '10'],
            ['oficina_id' => '11'],
            ['oficina_id' => '12'],
            ['oficina_id' => '13'],
            // ['oficina_id' => '14'],
            ['oficina_id' => '15'],
            ['oficina_id' => '16'],
            ['oficina_id' => '17'],
            ['oficina_id' => '18'],
            ['oficina_id' => '19'],
            ['oficina_id' => '20'],
            ['oficina_id' => '21'],
            ['oficina_id' => '22'],
            ['oficina_id' => '23'],
            ['oficina_id' => '24'],
            // ['oficina_id' => '25'],
            ['oficina_id' => '26'],
            ['oficina_id' => '27'],
            ['oficina_id' => '28'],
            ['oficina_id' => '29'],
            ['oficina_id' => '30'],
            ['oficina_id' => '31'],
            ['oficina_id' => '32'],
            ['oficina_id' => '33'],
            ['oficina_id' => '34'],
            ['oficina_id' => '35'],
            // ['oficina_id' => '36'],
            ['oficina_id' => '37'],
            ['oficina_id' => '38'],
            ['oficina_id' => '39'],
            ['oficina_id' => '40'],
            ['oficina_id' => '41'],
            ['oficina_id' => '42'],
            ['oficina_id' => '43'],
            ['oficina_id' => '44'],
            ['oficina_id' => '45'],
            ['oficina_id' => '46'],
            // ['oficina_id' => '47'],
            ['oficina_id' => '48'],
            ['oficina_id' => '49'],
            ['oficina_id' => '50'],
            ['oficina_id' => '51'],
            ['oficina_id' => '52'],
            ['oficina_id' => '53'],
            ['oficina_id' => '54'],
            ['oficina_id' => '55'],
            ['oficina_id' => '56'],
            ['oficina_id' => '57'],
            // ['oficina_id' => '58'],
            ['oficina_id' => '59'],
            ['oficina_id' => '60'],
            ['oficina_id' => '61'],
            ['oficina_id' => '62'],
            ['oficina_id' => '63'],
            ['oficina_id' => '64'],
            ['oficina_id' => '65'],
            ['oficina_id' => '66'],
            ['oficina_id' => '67'],
            ['oficina_id' => '68'],
            // ['oficina_id' => '69'],
            ['oficina_id' => '70'],
            ['oficina_id' => '71'],
            ['oficina_id' => '72'],
            ['oficina_id' => '73'],
            ['oficina_id' => '74'],
            ['oficina_id' => '75'],
            ['oficina_id' => '76'],
            ['oficina_id' => '77'],
            ['oficina_id' => '78'],
            ['oficina_id' => '79'],
            ['oficina_id' => '70'],
            ['oficina_id' => '71'],
            ['oficina_id' => '72'],
            ['oficina_id' => '73'],
            ['oficina_id' => '74'],
            ['oficina_id' => '75'],
            ['oficina_id' => '76'],
            ['oficina_id' => '77'],
        ))->create(['dia_id' => '4',
                  'horario_inicio' => '08:00:00',
                  'horario_fin' => '12:00:00',
                  'cant_max_turno' => 5,
                  'intervalo_turno' => '60',]);                   

    }
}
